### ISSUE TITLE
Library support CSS tag?

### ISSUE THREAD

**Issue by Ashok701** [UttamPanchasara/PDF-Generator#11]
like bootstrap.

**Comment by Ashok701** [comment]
like bootstrap

**Comment by UttamPanchasara** [comment]
Hi,
Have you try by passing HTML content with css tags to library?

**Comment by Ashok701** [comment]
Thanks for your reply.

No, I just ask you because now i facing PDF under padding issue in many devices.

Please check below link.

https://drive.google.com/file/d/1Q6yeYr2vOcyrn9vaDBgXd3yIsHOZTNP1/view

**Comment by UttamPanchasara** [comment]
There must be something else with your HTML + CSS file, because I'm not adding any external padding or something. If you can share some code(content) to reproduce this issue then I can take a look.

**Comment by Ashok701** [comment]
yes sure, that sounds good, but as per my company norms i can not share my code with you in public so please give me your email id.
here is my email id, please send me the email, i will revert back you with the code.
gohelashok701@gmail.com

**Comment by UttamPanchasara** [comment]
Code means would like to have the content which you are passing to the library and generating PDF, 
Email id: panchasarauttam@gmail.com

**Comment by Ashok701** [comment]
I shared content file to panchasarauttam@gmail.com.

**Comment by Ashok701** [comment]
I hope you update me ASAP.

Thanks.

**Comment by Ashok701** [comment]
Hello Uttam Panchasara,

I found issue from html content.
now it's working fine.

Thanks
Ashok
