### ISSUE TITLE
File saved as "namefile.pdf.pdf"

### ISSUE THREAD

**Issue by Calistex** [UttamPanchasara/PDF-Generator#15]
Hello @UttamPanchasara, thank you for this beautiful library, it's saving me so much time.

When I try to generate a pdf, using .openPrintDialog(true), and try saving the pdf in the internal memory of my phone, the file will be saved as "namefile.pdf.pdf".
I checked the .setPdfName() and I don't pass any string that ends with ".pdf".

Here is an example:
![code](https://user-images.githubusercontent.com/11682775/83353435-e00fd080-a352-11ea-843f-0a68e4ae2620.png)

![debug](https://user-images.githubusercontent.com/11682775/83353442-e736de80-a352-11ea-96ee-2a946f67e429.png)

![screenshot](https://user-images.githubusercontent.com/11682775/83353446-ebfb9280-a352-11ea-95d8-d8a8036993c3.png)

Could this line be the problem?
https://github.com/UttamPanchasara/PDF-Generator/blob/58bffe4c04498f85950c46dbd36ffd21c2e3782a/pdfgenerator/src/main/java/com/uttampanchasara/pdfgenerator/CreatePdf.kt#L38

Thank you for your time.

**Comment by UttamPanchasara** [comment]
Thanks for using this library and sorry for delay, Please debug and recheck your code because it working fine here not adding any extra format to name.
Closing this as I'm not seeing any issue in library, Feel free and re-open or create new issue.
