### ISSUE TITLE
Custom saved file location.

### ISSUE THREAD

**Issue by ankurtagtaste** [UttamPanchasara/PDF-Generator#2]
Is it possible to pass the location where I need to download the file?

**Comment by UttamPanchasara** [comment]
Sorry but that is not possible for the current version, by default it will save a file in cache directory only and then if you want that file somewhere else you will have to move/copy that file to the specific location.

**Comment by UttamPanchasara** [comment]
Hi,

Please check the updated version of the library, now you will have the option to set your own file storage location.

Thanks
