### ISSUE TITLE
need of java compatible

### ISSUE THREAD

**Issue by rajam1215** [UttamPanchasara/PDF-Generator#3]
How to use this library in java code. it is very good library but i need in java. please give me solution. coz its need java compatibility.

**Comment by UttamPanchasara** [comment]
Hi, 

Here is code to use the library with JAVA it's really very easy to use :

In kotlin we don't need to use `new` keyword but in JAVA we required.

    new CreatePdf(this)
                .setPdfName("FirstPdf")
                .openPrintDialog(false)
                .setContentBaseUrl(null)
                .setContent("Your Content")
                .setCallbackListener(new CreatePdf.PdfCallbackListener() {
                    @Override
                    public void onFailure(@NotNull String s) {
                        // handle error
                    }

                    @Override
                    public void onSuccess(@NotNull String s) {
                        // do your stuff here
                    }
                })
                .create();


Thanks

**Comment by rajam1215** [comment]
Hello Uttam

 i already do from my self. before your solution in code. i think you give more enhancement for java.
so i don't close  it from my self, thanks again for reply but i create one more issue for library, it is come when i give very Hugh data for print PDF with HTML, this time it gives error. Please check in your issue (Bug) board.

Thanks
