### ISSUE TITLE
need progress bar when generate pdf

### ISSUE THREAD

**Issue by rajam1215** [UttamPanchasara/PDF-Generator#5]
Hello Uttam

I am very glad to use your library for PDF generation. i want one more minor enhancement in library.
when we click on button for PDF generation. need to show some processing with progressDialogBar. when library work we don't have any access to show progress bar or other, because that time your code work in background thread, please check.

Thanks again

**Comment by UttamPanchasara** [comment]
Hello,

Thanks for your suggestion and surely will implement, by the time you can still show progress as I'm giving callback on pdf generation process complete, so you can start progress just before calling CreatePdf method and on completion, you can hide.

Thanks

**Comment by rajam1215** [comment]
Hello uttam
Thanks for giving very fast reply and solution.

**Comment by rajam1215** [comment]
hello @UttamPanchasara 

I close this issue, because i think giving solution is good enough to handling show progress bar when PDF generate. but you can enhance more feature in future in this library.

Thanks
