### ISSUE TITLE
Can not create (Generate) Table 

### ISSUE THREAD

**Issue by xyz996** [UttamPanchasara/PDF-Generator#8]
what about creating table with specified rows and columns 
for example to generate an Invoice you need a table to put items or what ever in it

**Comment by UttamPanchasara** [comment]
Hi,

In this library you don't have such functionalities as In this I'm only generating PDF from provided contents like HTML or String, If you want to generate Invoice with table format you will have to create HTML view for same with data and then pass to Library and you will have your PDF.

I'm closing this issue as It's not relevant to this.

Thanks.
