### ISSUE TITLE
How can i cancel PDF on time of creating?

### ISSUE THREAD

**Issue by Ashok701** [UttamPanchasara/PDF-Generator#9]
creating large PDF it's take much time.

**Comment by UttamPanchasara** [comment]
Can you please share your content how large it is?

**Comment by Ashok701** [comment]
Hello UttamPanchasara/PDF-Generator

Thanks for your reply.

Now i resolved the issue.

Thanks and Regards,
Ashok

**Comment by UttamPanchasara** [comment]
Thanks for updating on the issue, as you have solved the issue i'm closing this.
